version: "3"

networks:
  web:
    external: true

services:
  noop:
    image: nginx
    restart: always
    volumes:
      - ./site:/usr/share/nginx/html:ro
    networks:
      - web
    labels:
      - traefik.backend=murderer
      - traefik.docker.network=web
      - traefik.port=80

